[versions]
paper-api = "1.21-R0.1-SNAPSHOT"
lombok = "1.18.34"
shadow = "8.3.0"
placeholderapi = "2.11.6"
run-paper = "2.3.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }